### ISSUE TITLE
Incorrect Major for ianbgilbert

### ISSUE THREAD

**Issue by liam-middlebrook** [FOSSRIT/FOSSProfiles#23]
@ianbgilbert has their major set as what looks like an email address. [source](https://github.com/FOSSRIT/FOSSProfiles/blob/master/profiles/student/ianbgilbert.yaml#L3)

**Comment by msoucy** [comment]
@ianbgilbert , pull request to fix?

**Comment by ryansb** [comment]
See #25

**Comment by liam-middlebrook** [comment]
Fixed via #27
