### ISSUE TITLE
Update profiles

### ISSUE THREAD

**Issue by thewileyside** [FOSSRIT/FOSSProfiles#24]
@Nolski it's all you

**Comment by Nolski** [comment]
What exactly need to be updated?

**Comment by thewileyside** [comment]
last time i saw your stuff none of your links or anything worked

**Comment by jflory7** [comment]
I give a +1 to close this issue. I don't think it's still relevant – all of the URLs in @Nolski's YAML file are valid and appear to be functioning.

**Comment by Nolski** [comment]
This was my fault. My server was in a state of flux when this was opened. Thanks for the note @thewileyside :)

**Comment by jflory7** [comment]
@Nolski++
