### ISSUE TITLE
Maybe people don't have a blog

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/FOSSProfiles#40]
Proposing renaming `blog:` in the `.yml` files to `site:`, or just adding the latter.

**Comment by jflory7** [comment]
@ct-martin That's fair. I'll work on updating this in a future PR. It will require all existing YAMLs to be edited.

**Comment by ct-martin** [comment]
You could also make it optional, people may have a blog hosted on wordpress.com but no plain site (or maybe they only have people.rit.edu, but don't want to make it public), and they just want to work off their GitHub repo.
